# -*- coding: utf-8 -*-
"""euclidean_distance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11673bx9baH4UHkLMdgi0ZyxfmEhXr6u3
"""

print('      n')
print('sqrt( \u2211' + '    (ai - pi)^2 )')
print('      i=1')

from sympy import Sum, symbols, Indexed, lambdify
import numpy as np

x, i = symbols("x i")
s = Sum(Indexed('x',i),(i,0,3))
f = lambdify(x, s)
b = np.array([1, 2, 3, 4])
f(b)

from math import sqrt

plot1 = [1,3]
plot2 = [2,5]

euclidean_distance = sqrt( (plot1[0] -plot2[0])**2 + (plot1[1] -plot2[1])**2 )
print(euclidean_distance)