# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JaHLRKczJoUN-cymnkiJW4fLLvWVu-kX
"""

# $ Linear Regression
# Take continuous data and figure out a best fit line to that data
# Features and Labels - Important in Supervised Learning
# Quandl gives you lots of data sets - limited calls per day without an account


!pip install sklearn
!pip install quandl
!pip install pandas

import pandas as pd
import quandl

df = quandl.get('WIKI/GOOGL')
print(df.head())

# Open, High, Low, Close, Volume are all features

# Can discover relationships between attributes in deep learning, but not with regression
# You want to simplify your data as much as possible, useless data can cause problems with your classification

df = df[['Adj. Open', 'Adj. High', 'Adj. Low', 'Adj. Close', 'Adj. Volume']]

# Open tells us the opening price of a stock for the day
# The relationship between High and Low, tells us the volatility for the day
# Close tells us if it went up or down from the Open Price
# Volume is the number of trades made that day

# $ Percent Volatility

# The dividend is subtracting low from high, row by row
df['HighLowPercent'] = (df['Adj. High'] - df['Adj. Close']) / df['Adj. Close'] * 100.0
df['PercentChange'] = (df['Adj. Close'] - df['Adj. Open']) / df['Adj. Open'] * 100.0
df = df[['Adj. Close', 'HighLowPercent', 'PercentChange', 'Adj. Volume']]

print(df.head)